# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8IP1ksKvHayNydSiYfmurLYK4Nbz1BD
"""

#1. Find sum of first 10 natural numbers
n=10
sum=0
for i in range(1,n+1):
  sum += i
print("Sum:",sum)

#2. Find Factorial of a number
num=int(input("Enter a number:"))
factorial=1
for i in range(1, num+1):
  factorial= factorial*i
print("Factorial:", factorial)

#3. Print fibonacci series
n=int(input("Enter number of terms:"))
a=0
b=1
print("Fibonacci series:")
for i in range(n):
  print(a,end="")
  c=a+b
  a=b=c

#4. Find the largest among 3 numbers
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))
if a>=b and a>=c:
  largest=a
elif b>=a and b>=c:
  largest=b
else:
  largest=c
print("Largest number:", largest)

#5. Create Student result system
name= input("Enter a name:")
roll_no= int(input("Enter roll number:"))
total=0
for i in range (1,6):
  marks=float(input(f"Enter marks for subject {i}:"))
  total += marks
percentage= total/5
if percentage >= 90:
  grade="A"
elif percentage >=80:
  grade= "B"
elif percentage >=70:
  grade="C"
elif percentage >=60:
  grade="D"
else:
  grade=F
print("Name:", name)
print("Roll No:", roll_no)
print("Total marks:", total)
print("Percentage:", percentage)
print("Grade:", grade)

