# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8IP1ksKvHayNydSiYfmurLYK4Nbz1BD
"""

#1. Create a function to print first 10 natural numbers
def print_natural_numbers():
   for i in range (1,11):
    print(i)
print_natural_numbers()

#2. Create a function to calculate sum of first N natural numbers
def sum_natural_number(n):
  total=0
  for i in range(1,n+1):
    total+=i
  return total
n=int(input("Enter a number:"))
result= sum_natural_number(n)
print("Sum:", result)

#3. Create a function to reverse a number
def reverse_number(num):
  reverse=0
  while num>0:
    digit=num%10
    reverse=reverse*10 + digit
    num=num//10

  return reverse
num=int(input("Enter a number:"))
result=reverse_number(num)
print("Reverse number:", result)

#4. Create a function to count digit in a number
def count_digits(num):
    count = 0
    while num > 0:
        count += 1
        num = num // 10
    return count
num = int(input("Enter a number: "))
result = count_digits(num)
print("Number of digits =", result)

#5. Create a function to check palindrome number
def is_palindrome(num):
    original = num
    reverse = 0
    while num > 0:
        digit = num % 10
        reverse = reverse * 10 + digit
        num = num // 10
    if original == reverse:
        return True
    else:
        return False
num = int(input("Enter a number: "))
if is_palindrome(num):
    print("Palindrome Number")
else:
    print("Not a Palindrome Number")

#6. Create a function to generate fibonacci series
def fibonacci(n):
    a = 0
    b = 1
    for i in range(n):
        print(a, end=" ")
        c = a + b
        a = b
        b = c
n = int(input("Enter the number of terms: "))
fibonacci(n)

#7. Calculator using function
def add(a, b):
    return a + b
def subtract(a, b):
    return a - b
def multiply(a, b):
    return a * b
def divide(a, b):
    return a / b
print("Calculator")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
choice = int(input("Enter your choice: "))
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
if choice == 1:
    print("Result =", add(num1, num2))
elif choice == 2:
    print("Result =", subtract(num1, num2))
elif choice == 3:
    print("Result =", multiply(num1, num2))
elif choice == 4:
    if num2 != 0:
        print("Result =", divide(num1, num2))
    else:
        print("Cannot divide by zero")
else:
    print("Invalid Choice")

#8. Create a text file and store student details
name = input("Enter student name: ")
roll_no = int(input("Enter roll number: "))
course = input("Enter course: ")
marks = int(input("Enter marks: "))
file = open("student.txt", "w")
file.write("Student Name: " + name + "\n")
file.write("Roll Number: " + roll_no + "\n")
file.write("Course: " + course + "\n")
file.write("Marks: " + marks + "\n")
file.close()
print("Student details are stored")

#9. Read data from a file
file = open("student.txt", "r")
data = file.read()
print(data)
file.close()

#10. Handle division by zero using exception handling
try:
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 / num2
    print("Result =", result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")

#11. Create a student class with name and marks
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks
student1 = Student("Tanisha", 85)
print("Name:", student1.name)
print("Marks:", student1.marks)