# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8IP1ksKvHayNydSiYfmurLYK4Nbz1BD
"""

#1. Find area of rectangle
length= int(input("Enter the length of the rectangle:"))
breadth=int(input("Enter the breath of the rectangle:"))
area= length*breadth
print("Area of the rectangle:", area)

#2. Find simple interest
principle_amount=int(input("Enter the principle amount:"))
rate_of_interest= float(input("Enter the rate of interest:"))
time_period=float(input("Enter the time period:"))
simple_interest= (principle_amount* rate_of_interest* time_period)/100
print("Simple Interest:",simple_interest)

#3. Convert temperature from celsius to fahrenheit

celsius=float(input("Enter the temperatue in celsius:"))
fahrenheit= (celsius*9/5)+32
print("Temperature in Fahrenheit:", fahrenheit)

#4. Calculate average of 3 numbers
num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))
num3=int(input("Enter third number:"))
avg= (num1+num2+num3)/3
print("Average of 3 numbers:", avg)

#5. Find square and cube of a number
num=int(input("Enter a number:"))
sqr= num**2
cube=num**3
print("Square:", sqr)
print("cube:", cube)

#Swap two variables without third variable
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("Before swapping:")
print("a=",a)
print("b=",b)
a,b=b,a
print("After swapping:")
print("a=",a)
print("b=",b)

#7. Create a student report progrm that take student  details using input(), store marks in variable, calculate total and percentage, use comments, use proper indentation
#Student Report Program

# Input student details
student_name = input("Enter student name: ")
roll_no = input("Enter roll number: ")

# Input marks for 5 subjects
mark1 = float(input("Enter marks for Maths: "))
mark2 = float(input("Enter marks for Physics: "))
mark3 = float(input("Enter marks for chemistry: "))
mark4 = float(input("Enter marks for English: "))
mark5 = float(input("Enter marks for Physical Education: "))

# Calculate total marks
total = mark1 + mark2 + mark3 + mark4 + mark5

# Calculate percentage
percentage = total / 5

# Display student report
print("Student Name :", student_name)
print("Roll Number  :", roll_no)
print("Total Marks  :", total)
print("Percentage   :", percentage, "%")

# Display result
if percentage >= 40:
    print("Result       : PASS")
else:
    print("Result       : FAIL")